# Site settings
baseurl = "https://www.mariapitadefcon.es/"
#baseurl = "https://uxio0.github.io/mpdefcon_web/"
languageCode = "es-es"
title = "María Pita DefCon"
theme = "hugo-agency-theme"

# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-90759484-1"

[params]
  # You can use Markdown syntax for urls [text](//url.to/source) or
  # most longer texts.
  #
  # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # To provide some metadata for search engines feel free to add a few
  # information about you and your website.
  name = "María Pita DefCon"
  description = "Evento centrado en la seguridad informática y la visibilización de la mujer en dicho ámbito en A Coruña"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Possibility to disable external/additional fonts
  # Exception: Fontawesome
  disableFonts = false

  # 404 error customization
  [params.error404]
    heading = "Tal vez te has pasado con las comillas ;)"
    text = "Por favor vuelve a la [página principal](http://www.mariapitadefcon.es/)"

  # Optional piwik tracking
  #[params.analytics.piwik]
  #  URL = "https://stats.example.com"
  #  ID = "42"
  #  # Track all subdomains with "*.example.com"
  #  domain = "www.example.com"
  #  # Optional integrity check hash
  #  hash = "sha512-RfeD0pacGTqy9m7U6PgehQfS4cc7SIt+e+P+H5e848kEvB/RW84CUGO3O4O3LNbxjevym6KPUZ8muPsMrI8WIw=="

  [params.ogtags]
  image = '/img/siteLogo/logo.png'
  description = 'Evento centrado en la seguridad informática y la visibilización de la mujer en dicho ámbito. Se celebrará del 6 al 12 de marzo de 2017 en la Facultade de Informática de la Universidade da Coruña'

  # Navigation
  [params.navigation]
    brand = "María Pita DefCon"
    # Optional logo as brand stored in img/
    #logo = "logo.svg"
    services = "¿Qué es?"
    registration = "Registro"
    schedule = "Programa"
    portfolio = "Ponentes"
    about = "Historia"
    team = "Equipo"
    contact = "Contacto"
    coTeam = "Colaboradores"

    # Add custom links. Those can be pre- and postpended to the default menu above.
    # Use the weight attribute to order your custom links. Uncomment the example
    # below and replace the values with your own.

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    # [[menu.postpend]]
    #   url = "fixed/colaboradores/"
    #   name = "Colaboradores"
    #   weight = 10

  # Hero section
  [params.hero]
    # To change the background image of the hero, replace 'header-bg.jpg' in
    # the 'static/img' folder.
    title = "María Pita DefCon"
    subtitle = ""
    buttonText = "¡Regístrate ya!"
    url = "https://mariapitadefcon.eventbrite.es"


  # Services section
  [params.services]
    enable = true
    title = "¿Qué es?"
    mapsIframe = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2902.1118216225314!2d-8.413077584226615!3d43.33284908110404!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xd2e7cb3d82865e7%3A0x426ea83b7a5a451f!2sFacultad+de+Inform%C3%A1tica+-+UDC!5e0!3m2!1ses!2ses!4v1485284149515"
    subtitle = """
**María Pita DefCon** es un evento centrado en la **seguridad informática** y la **visibilización de la mujer** en dicho ámbito, que tendrá lugar en la **Facultade de Informática** de la Universidade da Coruña del **6** al **12** de **marzo** de 2017.

En él se darán cita los mejores ponentes del mundo de la seguridad informática tanto a nivel **local** como **nacional**.

Con una participación estimada de más de **500 visitantes únicos**, contará con numerosas charlas, mesas redondas y talleres a lo largo de toda una semana.

Durante el evento tendrá lugar el **María Pita DefCon Trileuco Contest**, donde podrás aprender y poner a prueba tus habilidades en materia de seguridad con diferentes retos y, además, terminará con una prueba presencial."""

    [[params.services.row]]

    [[params.services.row.list]]
      icon = "fa-paper-plane-o"
      title = "CFP"
      description = """
¿Tienes una **charla, taller, mesa redonda o concurso** sobre seguridad que quieras presentar a un público interesado?

El call for papers permanecerá **abierto desde el 9 de enero al 6 de febrero (ambos inclusive)**.

[Sigue este enlace para más información](/fixed/cfp)
"""
      url = "#"

    [[params.services.row.list]]
      icon = "fa-users"
      title = "Voluntarios"
      description = """
Desde la Organización del evento, **buscamos voluntarios** que quieran echar una mano con cualquier tarea relacionada con la organización del mismo.

Si estás **interesado en colaborar** como voluntario, rellena el [siguiente formulario](http://voluntarios.mariapitadefcon.es/). Nos pondremos en contacto contigo en el menor tiempo posible. ¡Gracias!
"""
      url = "#"

    [[params.services.row.list]]
      icon = "fa-id-card-o"
      title = "Registro"
      description = """
Una vez publicado el programa definitivo se abrirá el registro de asistentes.

**La inscripción y la aceptación del [código de conducta](/fixed/conducta) serán de carácter obligatorio** para poder participar en el evento.
"""
      url = "#"

  # Registration section
  [params.registration]
  enable = true
  title = "Registro"
  subtitle = "Inscripción para las charlas y talleres"

    [params.registration.talks]
    enable = true
    buttonText = "Charlas"
    url = "https://mariapitadefcon.eventbrite.es"

    [params.registration.workshops]
    enable = false
    buttonText = "Talleres"
    disableHelp = "*Se abrirá el plazo en los próximos días"
    url = ""

  # Schedule section
  [params.schedule]
    enable = true
    title = "Programa"
    subtitle = "Charlas y talleres"
    file = "pdf/programa-mariapitadefcon-2017.pdf"

  # Portfolio section
  [params.portfolio]
    enable = true
    # All projects defined in their own files. You can find example projects
    # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    title = "Ponentes"
    subtitle = "Ponentes confirmados para María Pita DefCon 2017"

    [params.portfolio.modal]
      client = "Client"
      date = "Date"
      category = "Category"
      buttonText = "Cerrar"


    # About section
  [params.about]
    enable = true
    title = "Historia"
    subtitle = ""
    endpoint = "Tú también puedes ser parte!"

    # The events will be listed from the top to the bottom.
    # All images are stored under 'static/img/about'.
    # Replace them with your own.
    [[params.about.events]]
      img = "1.jpg"
      date = "Noviembre de 2016"
      title = "Nace María Pita DefCon"
      description = "Debido al hueco que dejan en Coruña unas conferencias de temática similar, nace la idea de unas nuevas conferencias"

    [[params.about.events]]
      img = "2.jpg"
      date = "28 de Diciembre de 2016"
      title = "Publicación de la nota de prensa"
      description = "El día de los inocentes se publica la primera nota de prensa de la celebración de las jornadas, tras la confirmación de la colaboración de la Facultade de Informática de A Coruña. Tal vez no haya sido la mejor fecha para anunciarla..."

    [[params.about.events]]
      img = "3.jpg"
      date = "6 Enero de 2016"
      title = "Abre CFP y patrocinios"
      description = "Se abre el Call for Papers, así como la búsqueda de patrocinadores/voluntarios para las jornadas"

    [[params.about.events]]
      img = "3.jpg"
      date = "6 Febrero de 2016"
      title = "Cierra CFP"
      description = "Se cierra el Call For Papers"


    [[params.about.events]]
      img = "4.jpg"
      date = "6-12 Marzo de 2016"
      title = "Jornadas María Pita DefCon"
      description = "Celebración de las jornadas"


  # Team section
  [params.team]
    enable = true
    # Possibility to center items
    center = true
    title = "Equipo"
    subtitle = "Organización del evento"
    description = ""

    # All team member's pictures are stored under 'static/img/team'.
    # Replace them with your own too.
    # Suggestion: Image size should be at least 360px*360px or the alignment might be affected.
    [[params.team.members]]
      img = "alejo.jpg"
      name = "Alejo Pacín"
      #position = "Ingeniero Informático"
      #reportsTo = ""
      #livesIn = "[A Coruña, España](#some-maps-url)"
      #scope = [
      #  "Investigador de seguridad"
      #]
      # For bio markdown and even multiline strings are available.
      bio = ""
      social = [
        ["fa-twitter", "https://twitter.com/xuco86"],
        ["fa-github", "https://github.com/alejopj"],
        ["fa-linkedin", "https://es.linkedin.com/in/alejopj"]
      ]

    [[params.team.members]]
      img = "uxio.jpg"
      name = "Uxío Fuentefría"
      #position = "Ingeniero Informático"
      #livesIn = "[A Coruña, España](#some-maps-url)"
      #scope = [
      #  ""
      #]
      social = [
        ["fa-twitter", "https://twitter.com/uxio0"],
        ["fa-github", "https://github.com/Uxio0"],
        ["fa-linkedin", "https://es.linkedin.com/in/uxiof"]
      ]

    [[params.team.members]]
      img = "david.jpg"
      name = "David Albela"
      position = ""
      social = [
        ["fa-twitter", "https://twitter.com/dalbela"],
        ["fa-github", "https://github.com/dalbelap"],
        ["fa-linkedin", "https://es.linkedin.com/in/david-albela-6591399a"]
      ]

    [[params.team.members]]
      img = "daniel-somoza.png"
      name = "Daniel Somoza"
      position = ""
      social = [
        ["fa-building-o", "http://www.aulanosa.es/"],
        ["fa-twitter", "https://twitter.com/DaniSomoza_"]
      ]

    [[params.team.members]]
      img = "pilar_vila.jpg"
      name = "Pilar Vila"
      position = ""
      social = [
        ["fa-building-o", "http://forensic-security.com/"]
      ]

    [[params.team.members]]
      img = "naya.jpg"
      name = "José Vázquez Naya"
      position = ""
      social = [
        ["fa-twitter", "https://twitter.com/vazqueznaya"],
        ["fa-linkedin", "https://es.linkedin.com/in/vazqueznaya"]
      ]

    [[params.team.members]]
      img = "raul.jpg"
      name = "Raúl Oróns"
      position = ""
      social = [
        ["fa-linkedin", "https://es.linkedin.com/in/raul-oc/en"]
      ]

    [[params.team.members]]
      img = "fernando_suarez.jpg"
      name = "Fernando Suárez Lorenzo"
      position = ""
      social = [
        ["fa-linkedin", "https://es.linkedin.com/in/fernando-su%C3%A1rez-lorenzo-32519b8"]
      ]

    [[params.team.members]]
      img = "mr_robot.jpg"
      name = "Juan González Cid"
      position = ""
      social = [
        ["fa-linkedin", "https://es.linkedin.com/in/juan-jose-gonzalez-cid-21179714/en"]
      ]

    [[params.team.members]]
      img = "dani_cambon.jpg"
      name = "Daniel Cambón Parrado"
      position = ""
      social = [
        ["fa-linkedin", "https://es.linkedin.com/in/danielcambon"]
      ]

    [[params.team.members]]
      img = "monica.jpg"
      name = "Mónica Rodríguez Fernández"
      position = ""
      social = [
        ["fa-linkedin", "https://es.linkedin.com/in/monicarodriguezfernandez"]
      ]

    [[params.team.members]]
      img = "raul_rodriguez_rubio.jpg"
      name = "Raúl Rodríguez Rubio"
      position = ""

    [params.coTeam]
    enable = true
    title = "Organiza"


      [[params.coTeam.members]]
        logo = "RNASA.png"
        alt = "RNASA-IMEDIR"
        link = "http://rnasa.tic.udc.es/presentacion.html"

      [[params.coTeam.members]]
        logo = "fic.jpg"
        alt = "Facultade de Informática de A Coruña"
        link = "http://www.fic.udc.es"

      [[params.coTeam.members]]
        logo = "cpeig.png"
        increaseLogoSize = true
        alt = "Colexio Profesional de Enxeñaría en Informática de Galicia"
        link = "https://www.cpeig.gal"



  # Client section
    [params.clients_list]
      enable = true
      title = "Colaboradores"
      # Possibility to center items
      center = true
      inscriptionLink = "fixed/colaboradores/"
      # Optional client title specifying the involvement
      #title = "Used and trusted by"

      # All the clients' logos are stored under 'static/img/logos'.
      # Replace them with your clients's logos.
      # Suggestion: .svg in the size of 280px*80px looks good
      [[params.clients.gold]]
        logo = "academia-postal.png"
        alt = "Grupo Academia Postal"
        link = "http://www.academiapostal.es"

      [[params.clients.gold]]
        logo = "trileuco.png"
        alt = "Trileuco Solutions"
        link = "http://trileucosolutions.com/"

      [[params.clients.gold]]
        logo = "aulanosa.png"
        alt = "Aula Nosa"
        link = "http://www.aulanosa.es"


      [[params.clients.gold]]
        logo = "telefonica.jpg"
        alt = "Telefónica"
        link = "https://www.telefonica.es/"

      [[params.clients.gold]]
        logo = "gradiant.jpg"
        alt = "Gradiant"
        link = "https://www.gradiant.org/"

      [[params.clients.gold]]
        logo = "forensic.png"
        alt = "Forensics & Security"
        link = "http://forensic-security.com/"

      [[params.clients.silver]]
        logo = "mobgen.jpg"
        alt = "Mobgen"
        link = "https://mobgen.com/"

      [[params.clients.silver]]
        logo = "symantec.png"
        alt = "Symantec"
        link = "https://www.symantec.com/es/es/"

      [[params.clients.silver]]
        logo = "ednon.png"
        alt = "Ednon"
        link = "http://ednon.com/"

      [[params.clients.bronze]]
        logo = "aldaba.png"
        alt = "Aldaba"
        link = "https://www.aldaba.es/"

      [[params.clients.bronze]]
        logo = "armada.png"
        alt = "Escuela de Especialidades Antonio Escaño"
        link = "http://www.armada.mde.es/ArmadaPortal/page/Portal/ArmadaEspannola/personal_escuelas/prefLang_es/04_escano--03_historia_es"

      [[params.clients.bronze]]
        logo = "balidea.jpg"
        alt = "Balidea"
        link = "http://www.balidea.com/"

      [[params.clients.bronze]]
        logo = "coremain.jpg"
        alt = "Coremain"
        link = "http://www.coremain.com/"

      [[params.clients.bronze]]
        logo = "emetel.png"
        alt = "Emetel"
        link = "http://www.emetel.net"

      [[params.clients.bronze]]
        logo = "oesia.jpg"
        maxHeight = "100px"
        alt = "Oesía"
        link = "http://grupooesia.com/"



  # Contact section
  [params.contact]
    enable = true
    title = "Contacto"
    subtitle  = "¿Quieres colaborar con el evento? ¿Tal vez aportar como voluntario? ¿Alguna duda?"
    buttonText = "Enviar mensaje"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!

    # It is possible to substitute formspring with other providers
    # as an example the mailout plugin from caddy.
    # Provide the post URL for the form and depending on the provider
    # add some custom JS script to finish the implementation.
    # postURL = "https://example.com/mailout/"

    email = "organizacion@mariapitadefcon.es"

    # Success and error message overwrite for async contact form
    thanks = "¡Gracias por contactarnos! Te contestaremos lo antes posible"
    error = "El mensaje no se pudo enviar. Por favor contáctanos en organizacion@mariapitadefcon.es"

    # 'warning' defines error messages for invalid inputs
    [params.contact.form.name]
      text = "Tu nombre *"
      warning = "Por favor introduce tu nombre"

    [params.contact.form.email]
      text = "Tu email *"
      warning = "Por favor introduce tu email"

    [params.contact.form.phone]
      text = "Tu teléfono"
      warning = ""

    [params.contact.form.message]
      text = "Tu mensaje *"
      warning = "Por favor escribe un mensaje"

      # Add optional form fields to identify contact forms
      #[[params.contact.form.hidden]]
      #  name = "someID"
      #  value = "example.com"
      #
      #[[params.contact.form.hidden]]
      # Special values for name such as "page" and "site" will be autofilled
      #  name = "page"

  # Footer section
  [params.footer]
    enable = true
    copyright = "Publicado bajo Licencia Apache 2.0."

    [[params.footer.social]]
      icon = "fa-twitter"
      link = "https://twitter.com/mariapitadefcon"

    [[params.footer.quicklinks]]
      text = "Código de conducta"
      link = "/fixed/conducta/"

    [[params.footer.quicklinks]]
      text = "Colaboradores"
      link = "/fixed/colaboradores/"
